export { client as api } from '../api'
export { authApi as authService } from '../api'
export { matchApi as matchService } from '../api'
export { scoringApi as scoringService } from '../api'
export { teamApi as teamService } from '../api'
export { statisticsApi as statisticsService } from '../api'
export { adminApi as adminService } from '../api'
export { playerApi as playerService } from '../api'
